id = "solar"
name = "Solar"
description = "Solidity support powered by Solar language server."
version = "0.1.0"
schema_version = 1
authors = ["Oliver Nordbjerg <hi@notbjerg.me>"]
repository = "https://github.com/onbjerg/zed-solar"

[language_servers.solar]
name = "Solar"
language = "Solidity"

[grammars.solidity]
repository = "https://github.com/JoranHonig/tree-sitter-solidity"
commit = "4ccd2b50ac2caaf8a97fc85ed4b10db4ce279a59"